### ISSUE TITLE
Add support for indirect use via android library

### ISSUE THREAD

**Issue by bbetter** [elastic/apm-agent-android#142]
I have multimodule application and I don't want to inject arm directly inside app module
Instead I want to be able to connect it to my android library module and abstract away lib initialization

**Comment by LikeTheSalad** [comment]
Thank you for your feedback, @bbetter 

If I understood correctly, it seems like manually adding the Elastic SDK into your library should sort your use case. We still haven't documented how to do so, but the dependency looks like the following:

```groovy
implementation "co.elastic.apm:android-sdk:0.4.0"
```

The version will always match the [Gradle plugin](https://plugins.gradle.org/plugin/co.elastic.apm.android) version.

After adding the SDK to your library, you can initialize it from there and it should work the same as if you'd have initialized it from your application. Bear in mind that, regardless of whether you initialize it from your application or your library, it is still recommended to apply the [Gradle plugin](https://plugins.gradle.org/plugin/co.elastic.apm.android) into your application so that you can get access to the [compile-time gradle configuration options](https://www.elastic.co/guide/en/apm/agent/android/current/configuration.html#_gradle_configuration), as well as automatic instrumentation support.

**Comment by LikeTheSalad** [comment]
The decision to have the min SDK version as 26 was made to make the setup process more straightforward and avoiding crashes on older devices. The reason why lowering it would make things more complicated is that the [OpenTelemetry SDK](https://github.com/open-telemetry/opentelemetry-java#requirements) uses some classes added in Java 8, which are not available on Android OS versions < Api level 26, on those devices the app would crash with a `NoClassDefFoundError` (like when running [this code](https://github.com/open-telemetry/opentelemetry-java/blob/fa46f19d3936512b652a8a2c5d0be39f29066802/exporters/common/src/main/java/io/opentelemetry/exporter/internal/grpc/GrpcExporterBuilder.java#L139) for example as the `java.time.Duration` is one of those newer classes).

There's a way to avoid this, though it would require adding extra dependencies and doing some extra compilation work as well, all of the details are explained [in here](https://developer.android.com/studio/write/java8-support#library-desugaring). We also weren't too sure if the API 26 was too "restrictive", since it seems to be available since [mid 2017](https://developer.android.com/studio/releases/platforms#8.0), so we ultimately ended up setting it as the min one and review that decision later in case some customers would require to lower it.

So based on it, I'm curious to know about your opinion on whether using the API level 26 nowadays is still too soon in general? If that's the case, we'll consider lowering it to 24.

**Comment by LikeTheSalad** [comment]
> It might be just our specific scenario to have to use a bit older version . So you're saying if I override library
> <uses-sdk tools:overrideLibrary/>
> and then add coreLibraryDesugaring
> it should save me from unexpected crashes?

That's correct.

> can I create this file by myself somewhere in my library root and let it be bundle with app for example
> and just specify environment in there?
> Or is the configuration without plugin impossible?

It's not impossible without the plugin, I'll create a couple of tickets to work on making the manual configuration smoother but in the meantime what you could do is:

- Create the asset file `co_elastic_apm_android.properties` inside your `src/main/assets` dir within your library.
- Add this line to that properties file: `service.deployment_environment=(your env name)`.
- Make sure to configure your backend connectivity params at runtime as explained [here](https://www.elastic.co/guide/en/apm/agent/android/current/configuration.html#_apm_server_connectivity).

It should make it work for now. We're continuously making new releases as we're still not GA, so the manual implementation process should improve quite soon.

**Comment by baudouxbenjamin** [comment]
I've the following defined in my library build.gradle.kts:
```kotlin
dependencies {
    implementation(libs.elastic.android)
}
```
with the following:
```toml
elastic-android = "1.13.1"
elastic-android = { group = "co.elastic.apm", name = "android-sdk", version.ref = "elastic-android" }
```
and I've the following error:
Unresolved reference: ElasticApmAgent
```kotlin
val agent = ElasticApmAgent.builder(application)
    .setServiceName("My app name")
    .setExportUrl("http://10.0.2.2:4318")
    .setExportAuthentication(Authentication.ApiKey("my-api-key"))
    .build()
```
What am I missing?

**Comment by LikeTheSalad** [comment]
Hi @baudouxbenjamin 

The coordinates have changed with version `1.0.0` (the version `1.13.1` was mistakenly released while trying to deploy version `0.13.1`, so the latest version now is `1.0.0`), take a look [here](https://central.sonatype.com/artifact/co.elastic.otel.android/agent-sdk) for the new ones.

Just for the record, it is recommended to [use the plugin](https://www.elastic.co/docs/reference/apm/agents/android/getting-started#gradle-setup) instead of manually adding the dependencies.

**Comment by baudouxbenjamin** [comment]
I have an `:app` module, which is my Android application module, and an `:elastic` module, which is an Android library module. Currently, I've applied the plugin in the `:app` module, but I'd like to configure everything in the `:elastic` module. How would you approach this project setup?

**Comment by baudouxbenjamin** [comment]
Also, when using the old version (0.20.0) whith the old api, I still get these errors even with minSdk = 26:
```
Dependency 'io.opentelemetry.android:instrumentation-lifecycle:0.5.0-alpha' requires core library desugaring to be enabled for :app.
```

**Comment by LikeTheSalad** [comment]
> I have an `:app` module, which is my Android application module, and an `:elastic` module, which is an Android library module. Currently, I've applied the plugin in the `:app` module, but I'd like to configure everything in the `:elastic` module. How would you approach this project setup?

I see what you mean. For this case it makes sense to add the sdk dependency directly into your library.

**Comment by LikeTheSalad** [comment]
> Also, when using the old version (0.20.0) whith the old api, I still get these errors even with minSdk = 26:

This is an issue inherited from the OTel Android version used on those old binaries. Version 1.0.0 shouldn't have this issue anymore.

**Comment by LikeTheSalad** [comment]
Versions `0.x` were a technical preview, so most of the features were incubating until `1.0.0` was released, for which some features were removed to start with a leaner, more stable API. Starting from version `1.0.0`, stability is top priority, though that carries a maintenance cost with it, so we wanted to make sure we focused on features that matter the most, such as disk buffering and real-time, for example, and will add more on top based on the feedback we get.

If I understood correctly, some of the features that you found useful from the tech preview are related to enabling/disabling automatic instrumentations, manually setting a sample rate, and setting an internal lib's logging policy. 

* For setting the sampling rate, there's no alternative yet, though it shouldn't be a complicated addition. If you don't mind creating an issue for it, where we can discuss some specific implementation details, I think we can include it in the next release.
* For automatic instrumentations, there's no configuration to disable them because there's no automatic instrumentation enabled by default. Instead, you'll need to add the ones you'd like to use in your app, as [explained here](https://www.elastic.co/docs/reference/apm/agents/android/automatic-instrumentation#installation) (btw these instrumentations must be added directly into your application gradle file, as they might need to do bytecode weaving, which is only possible when targeting android apps, not libraries. This is by AGP design). Note that only the okhttp automatic instrumentation is available at the moment, though we're planning to add support for OTel Android instrumentations so that they're compatible with the Elastic agent for the next release.
* You can set the agent's internal logging policy by using its `setInternalLoggingPolicy` builder method, as [shown here](https://www.elastic.co/docs/reference/apm/agents/android/configuration#internal-logging-policy).

**Comment by baudouxbenjamin** [comment]
> Versions `0.x` were a technical preview, so most of the features were incubating until `1.0.0` was released, for which some features were removed to start with a leaner, more stable API. Starting from version `1.0.0`, stability is top priority, though that carries a maintenance cost with it, so we wanted to make sure we focused on features that matter the most, such as disk buffering and real-time, for example, and will add more on top based on the feedback we get.
> 
> If I understood correctly, some of the features that you found useful from the tech preview are related to enabling/disabling automatic instrumentations, manually setting a sample rate, and setting an internal lib's logging policy.
> 
> * For setting the sampling rate, there's no alternative yet, though it shouldn't be a complicated addition. If you don't mind creating an issue for it, where we can discuss some specific implementation details, I think we can include it in the next release.
> * For automatic instrumentations, there's no configuration to disable them because there's no automatic instrumentation enabled by default. Instead, you'll need to add the ones you'd like to use in your app, as [explained here](https://www.elastic.co/docs/reference/apm/agents/android/automatic-instrumentation#installation) (btw these instrumentations must be added directly into your application gradle file, as they might need to do bytecode weaving, which is only possible when targeting android apps, not libraries. This is by AGP design). Note that only the okhttp automatic instrumentation is available at the moment, though we're planning to add support for OTel Android instrumentations so that they're compatible with the Elastic agent for the next release.
> * You can set the agent's internal logging policy by using its `setInternalLoggingPolicy` builder method, as [shown here](https://www.elastic.co/docs/reference/apm/agents/android/configuration#internal-logging-policy).

Thanks! I've created the issue here: [#480](https://github.com/elastic/apm-agent-android/issues/480). Regarding the instrumentations, there will be no issue if the actual initialization is done inside another module `:elastic` (as explained in my previous comment) while the gradle plugins (instrumentations and elastic-agent) are applied inside `:app`? I'm referring to this part:
```kotlin
val agent = ElasticApmAgent.builder(application)
    .setServiceName("My app name")
    .setExportUrl("http://10.0.2.2:4318")
    .setExportAuthentication(Authentication.ApiKey("my-api-key"))
    .build()
```

**Comment by LikeTheSalad** [comment]
> Regarding the instrumentations, there will be no issue if the actual initialization is done inside another module `:elastic` (as explained in my previous comment) while the gradle plugins (instrumentations and elastic-agent) are applied inside `:app`?

There should be no issue with that 👍
