### ISSUE TITLE
>= 0.14.0 version run failed

### ISSUE THREAD

**Issue by beiliubei** [elastic/apm-agent-android#289]
![image](https://github.com/elastic/apm-agent-android/assets/1127875/9b04e1cf-4da1-453b-8698-97e2aad9ed37)

**Comment by LikeTheSalad** [comment]
Hi @beiliubei 

It seems like it's happening due to version constraints we put in place to avoid enforcing newer compileSdk versions (inherited from the OTel Android SDK) on host projects as part of the switch from OTel Java to OTel Android.

It's been a while since that switch took place, so I believe we can remove the version constraints now without causing issues to several projects. Thank you for your feedback. I'm planning to release a new version this week with the constraints removed.

**Comment by LikeTheSalad** [comment]
Hi @beiliubei 

Version `0.16.0` is now available. It should contain a fix for the version constraint. Please feel free to reopen this issue if you still see it there!

Thank you for your patience.

**Comment by beiliubei** [comment]
@LikeTheSalad 
It's working. Thank you for the timely handling.
By the way, when upgrade from 0.13.0 to 0.16.0, I have to enable the **isCoreLibraryDesugaringEnabled** in the **compileOptions** and add the dependecy **coreLibraryDesugaring(libs.desugar.jdk.libs)**

https://developer.android.com/studio/write/java8-support.html

**Comment by LikeTheSalad** [comment]
Hi @beiliubei 

The enabling of desugaring requirement has been present for apps with minSdk < 26 since the beginning, however, in version `0.14.0` we made the requirement more explicit after extending [OTel Android](https://github.com/open-telemetry/opentelemetry-android), which enables it transitively.

The reason desugaring is needed is because [OTel Java](https://github.com/open-telemetry/opentelemetry-java), which is the core of this project, uses Java 8 tools that aren't available in Android versions below 8, so if your app targets those versions of Android, not enabling desugaring can cause your app to crash in those old versions due to classes or methods not found at runtime.
