### ISSUE TITLE
Is there an option to set up logging of HTTP requests manually?

### ISSUE THREAD

**Issue by agap** [elastic/apm-agent-android#301]
So I was able to set up Elastic's agent in our in a manual fashion, but now I'm wondering whether there's a way to set up HTTP logging manually.

I know I could probably just write my own network interceptor that would create spans and log data (sorry if I'm mixing different concepts here - I'm still new to Elastic) and set it up an all okhttp instances that exist in our app, but I'm wondering whether there is something that automates this task. I looked through all the classes that exist in `co.elastic.apm.android`, but couldn't find any implementations of okhttp's `Interceptor` interface.

Is there anything like that? Sorry if it's the wrong place to ask questions like this one.

**Comment by LikeTheSalad** [comment]
Hi!

This is the right place to ask them, so no worries about it :) 

It is possible to do so manually, although the documentation for it is not clear on this, since we're currently in the process of making a lot of big changes in OTel Android (and therefore in the Elastic agent too), which would make any detailed docs to quickly become stale/misleading. So I'm going to add a how-to guide here, although please bear in mind that we're currently working on the OTel Android architecture, so most likely the APIs will change soon to make them easier to use and more scalable.

The OkHttp instrumentation library lives [here](https://github.com/open-telemetry/opentelemetry-android/tree/main/instrumentation/okhttp/okhttp-3.0), in the OTel Android repo. What the Elastic agent currently does to add automatic OkHttp instrumentation is simply to apply said library (the way it's explained in its README). So, if you're interested in implementing automatic OkHttp instrumentation without using the Elastic agent gradle plugin you can do so by following the steps there in the OkHttp instrumentation README. If, however, you'd like to avoid any automatic instrumentation at all, then you could do the following:

- Add the [okhttp instrumentation library](https://github.com/open-telemetry/opentelemetry-android/tree/main/instrumentation/okhttp/okhttp-3.0#project-dependencies) dependency to your project (only the one added with `implementation`, ignore the `byteBuddy` one).
- When building your own OkHttp instance, add the interceptors that come within that library as shown [here](https://github.com/open-telemetry/opentelemetry-android/blob/21f0b1135e7fc05d1de08f71f9142ef21335962a/instrumentation/okhttp/okhttp-3.0/agent/src/main/java/io/opentelemetry/instrumentation/agent/okhttp/v3_0/OkHttpClientAdvice.java#L16). The most important ones are "CALLBACK_CONTEXT_INTERCEPTOR" (ensures to keep spans relationships across the okhttp threads), and "TRACING_INTERCEPTOR" (is the one that creates spans for okhttp requests).

And that's it, please let me know if you have any questions.

**Comment by agap** [comment]
Yeah, it seems to work, thanks again for such a quick response!

And totally understand your concerns regarding the documentation that becomes outdated quicker than you end up wrapping it up. :sweat_smile: Been there, done that, as they say.

I will be keeping an eye on updates of APM agent anyway, so thanks for the heads-up regarding your plans. :+1:
