### ISSUE TITLE
No HTTP requests showing either in logcat or elastic dashboard

### ISSUE THREAD

**Issue by baudouxbenjamin** [elastic/apm-agent-android#303]
Hi, we don't use the gradle plugin but we followed the instruction given [here](https://github.com/elastic/apm-agent-android/issues/301). So far we don't see any HTTP logs either in logcat nor in the elastic dashboard. We can see the logs regarding screen views (activity and fragment). What are we missing regarding the HTTP calls?

Here is what we have at the moment:
```kotlin
@Singleton
@ApplicationScope
class ObservabilityAgent @Inject constructor(
    application: Application
) {
    init {
        val connectivity = Connectivity.withSecretToken(BuildConfig.ELASTIC_SERVER_URL, BuildConfig.ELASTIC_SERVICE_TOKEN)
        val loggingPolicy = LoggingPolicy.enabled(LogLevel.TRACE)

        val config = ElasticApmConfiguration
            .builder()
            .setLibraryLoggingPolicy(loggingPolicy)
            .setDeploymentEnvironment(BuildConfig.ELASTIC_SERVICE_ENV)
            .setServiceName(BuildConfig.ELASTIC_SERVICE_NAME)
            .setServiceVersion(BuildConfig.ELASTIC_SERVICE_VERSION)
            .setSampleRate(0.5)
            .build()

        ElasticApmAgent.initialize(application, config, connectivity)
    }
}
```
and in our `OkHttpClient`:
```kotlin
private fun retrofit(adapter: HttpClientAdapter): Retrofit {
        val builder = okHttpClient.newBuilder()
            .addInterceptor(PlatformInterceptor())
            .addNetworkInterceptor(LogsInterceptor.newInstance(application))

        if (!builder.interceptors().contains(OkHttp3Singletons.CALLBACK_CONTEXT_INTERCEPTOR)) {
            builder.interceptors().add(0, OkHttp3Singletons.CALLBACK_CONTEXT_INTERCEPTOR);
            builder.interceptors().add(1, OkHttp3Singletons.RESEND_COUNT_CONTEXT_INTERCEPTOR);
            builder.interceptors().add(2, OkHttp3Singletons.CONNECTION_ERROR_INTERCEPTOR);
        }
        if (!builder.networkInterceptors().contains(OkHttp3Singletons.TRACING_INTERCEPTOR)) {
            builder.addNetworkInterceptor(OkHttp3Singletons.TRACING_INTERCEPTOR);
        }

        val client = builder.build()

        return Retrofit.Builder()
            .baseUrl(BuildConfig.WEB_SERVICE_BASE_URL)
            .client(client)
            .addConverterFactory(adapter.converter)
            .build()
}
```

**Comment by LikeTheSalad** [comment]
Hi @baudouxbenjamin 

It seems like your code is correct, so I would check the following:

- Please make sure you've called `ElasticApmAgent.initialize` before making any HTTP requests using the Retrofit instance that uses the customized okhttp client. This is because `ElasticApmAgent.initialize` sets the static [GlobalOpenTelemetry](https://github.com/open-telemetry/opentelemetry-java/blob/da4cd931f827bda109fa5a2f988472465cdc2a4c/api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java#L47) instance, which is later used by the [OkHttp3Singletons.TRACING_INTERCEPTOR](https://github.com/open-telemetry/opentelemetry-android/blob/8890dcb45055fa8115efd46968b5f180082982ca/instrumentation/okhttp/okhttp-3.0/library/src/main/java/io/opentelemetry/instrumentation/library/okhttp/v3_0/internal/OkHttp3Singletons.java#L36) to create the HTTP spans, and the order matters because if the `GlobalOpenTelemetry` instance is accessed before `ElasticApmAgent.initialize` is called, then your okhttp client will get a noop `OpenTelemetry` instance.
- The type of signal that we use to send HTTP telemetry is [span](https://opentelemetry.io/docs/concepts/signals/traces/#spans), which are not displayed as logs in Kibana but rather as APM transactions. You can find your app's transactions by navigating to `Observability/APM -> [your-app-name] -> Transactions` as shown below:

![Screenshot 2024-04-26 at 09 20 21](https://github.com/elastic/apm-agent-android/assets/56847527/1bb5fb7a-5f29-4cb9-a802-8c706362ef34)
![Screenshot 2024-04-26 at 09 20 56](https://github.com/elastic/apm-agent-android/assets/56847527/da5cd4a9-1054-4728-8394-09c6ea58a413)
![Screenshot 2024-04-26 at 09 21 22](https://github.com/elastic/apm-agent-android/assets/56847527/9c825c22-6e26-406d-a79c-834ae33a2b77)

I hope it helps.

**Comment by baudouxbenjamin** [comment]
Hi @LikeTheSalad 

Thanks for your quick response. I can see some transactions in the dashboard. Anyway to also see them in my logcat directly from Android Studio to make sure everything works fine without the need to wait for the events to start showing in the dashboard?

**Comment by baudouxbenjamin** [comment]
@LikeTheSalad I moved the `ElasticApmAgent.initialize` in first position in my application `onCreate` and I can now see the logs in logcat 🎉  Thank you !

**Comment by baudouxbenjamin** [comment]
Me again, sorry! Is there any way to rename the transactions name? For now everything is under `GET`. I'd like to have my transactions named `GET/my-service.be/data` for example.

**Comment by LikeTheSalad** [comment]
Unfortunately it's not possible at the moment, although it looks like a good feature request for the [OTel Android](https://github.com/open-telemetry/opentelemetry-android) project. If you don't mind creating an issue for it in there, I can bring it up in the next OTel Android sig meeing.
