### ISSUE TITLE
Clean up Maven from older but greater versions

### ISSUE THREAD

**Issue by almozavr** [elastic/apm-agent-android#348]
E.g. https://central.sonatype.com/artifact/co.elastic.apm/android-sdk-ktx/1.13.1 – 1.13.1 but is older than 0.20.0 – so it breaks such things as dependency updates checker (false positive of update is available) – any chance those outdated greater versions could be removed from maven?

**Comment by LikeTheSalad** [comment]
This was an unfortunate event where version `1.13.0` was released by mistake when the goal was to release version `0.13.0`. We contacted maven central on it and, suprisingly they agreed to remove the main library which is this one: https://repo1.maven.org/maven2/co/elastic/apm/android-sdk/ - It is surprising because they have strong policies about modifying non-snapshot artifacts. However, since this project has several modules (such as `android-sdk-ktx`), the submodule ones were not deleted, but it shouldn't mean a problem since the submodules are added automatically either as a transitive dependency of `android-sdk` or via our gradle plugin. Currently the functionality provided by `android-sdk-ktx` only makes sense when using [our plugin](https://plugins.gradle.org/plugin/co.elastic.apm.android), as it will take care of propagating span context across kotlin coroutine launches by relying on the extensions provided in `android-sdk-ktx`. If you're using our plugin, this dependency will get added automatically so it's not needed to explicitly add it to your project, and since our plugin doesn't have a version `1.13.0` artifact, your updates checker shouldn't prompt you to update to that version.

We're planning to do some adjustments to avoid any issues regarding this wrongly released version once we reach stability in version `1.0.0`, though in the meantime, as long as only the core lib (`android-sdk`) or the plugin is used, you shouldn't get false-positives about upgrading to `1.13.0`. Apologies for the inconvenience.
